cloud:
  aws:
    credentials:
      accessKey: AKIAVO3RZLXVCIFHMB72
      secretKey: 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
    region:
      static: "eu-west-2"
    stack:
      auto: false

application:
  bucket:
    name: antsiferov

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 335207099712-s06ka5s0ako05c8bd98jkiic0uel3bop.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile